server:
  port: 54321

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 회사 개인 로컬
    url: jdbc:mysql://localhost:3306/caeh_test
    username: root
    password: root123


  jpa:
    hibernate:
      ddl-auto: validate # create, create-drop, update, validate, none
#    show-sql: true
    properties:
      hibernate:
        show-sql: true # Spring 에서 Auto Configuration을 돕기 위해 jpa.hibernate 에서 설정할 수 있다면 jpa.properties.hibernate 에서 raw 하게 설정할 수도 있겠지?
        format_sql: true





